//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoninDigital.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoninDigital.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover your account.
        /// </summary>
        internal static string AccountRecoveryEmailSubject {
            get {
                return ResourceManager.GetString("AccountRecoveryEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoninDigital.Views.AdminView.
        /// </summary>
        internal static string AdminpageControlPath {
            get {
                return ResourceManager.GetString("AdminpageControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        internal static string AdminpageWindowTitle {
            get {
                return ResourceManager.GetString("AdminpageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoninDigital.Views.ConfirmationCodeView.
        /// </summary>
        internal static string ConfirmationCodeControlPath {
            get {
                return ResourceManager.GetString("ConfirmationCodeControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Code.
        /// </summary>
        internal static string ConfirmationCodeWindowTitle {
            get {
                return ResourceManager.GetString("ConfirmationCodeWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoninDigital.Views.ForgotPasswordView.
        /// </summary>
        internal static string ForgotPasswordControlPath {
            get {
                return ResourceManager.GetString("ForgotPasswordControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgotPassword.
        /// </summary>
        internal static string ForgotPasswordWindowTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We received a request to confirm your account. Your account confirmation code is: .
        /// </summary>
        internal static string GenericEmailContent {
            get {
                return ResourceManager.GetString("GenericEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoninDigital.Views.DashBoardView.
        /// </summary>
        internal static string HomepageControlPath {
            get {
                return ResourceManager.GetString("HomepageControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage GoninDigital.
        /// </summary>
        internal static string HomepageWindowTitle {
            get {
                return ResourceManager.GetString("HomepageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoninDigital.Views.LoginView.
        /// </summary>
        internal static string LoginControlPath {
            get {
                return ResourceManager.GetString("LoginControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoninDigital.Views.RegisterView.
        /// </summary>
        internal static string RegisterAccountControlPath {
            get {
                return ResourceManager.GetString("RegisterAccountControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your account.
        /// </summary>
        internal static string RegisterAccountEmailSubject {
            get {
                return ResourceManager.GetString("RegisterAccountEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Account.
        /// </summary>
        internal static string RegisterAccountWindowTitle {
            get {
                return ResourceManager.GetString("RegisterAccountWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoninDigital.Views.ResetPasswordView.
        /// </summary>
        internal static string ResetPasswordControlPath {
            get {
                return ResourceManager.GetString("ResetPasswordControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPasswordWindowTitle {
            get {
                return ResourceManager.GetString("ResetPasswordWindowTitle", resourceCulture);
            }
        }
    }
}
